name: Reproduce Detach Race Condition

on: [push]

jobs:
  run-race-condition:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Install Dependencies
        run: sudo apt-get install -y gcc make
        
      - name: Download DynamoRIO
        run: |
          # wget https://github.com/DynamoRIO/dynamorio/releases/download/release_6_0_0/DynamoRIO-Linux-6.0.0-6.tar.gz
          # tar -xzf DynamoRIO-Linux-6.0.0-6.tar.gz
          wget https://github.com/DynamoRIO/dynamorio/releases/download/cronbuild-10.91.19860/DynamoRIO-Linux-10.91.19860.tar.gz
          tar -xzf DynamoRIO-Linux-10.91.19860.tar.gz
      - name: Build Test Program
        run: |
          gcc -pthread -o race_test race_test.c

      - name: Run Test with DynamoRIO
        run: |
          echo "Running the test program under DynamoRIO..."
          # ./DynamoRIO-Linux-6.0.0-6/bin64/drrun -- ./race_test
          ./DynamoRIO-Linux-10.91.19860/bin64/drrun -- ./race_test
